Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriterTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: root123
  Host: 127.0.0.1:13306
  DBName: apple
  TablePrefix: apple_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30